### PR TITLE
Allow -cov to be used with dmd-transitional

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
New druntime tweak to prevent stomping prevention assert from being hit
from runtime code itself.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
LGTM. Should we try to push this upstream as well?

**Comment by mihails-strasuns-sociomantic** [comment]
> Should we try to push this upstream as well?

Would be nice, though I am not sure how to sell it :)

**Comment by nemanja-boric-sociomantic** [comment]
What's could be the harm in applying this patch? The benefit would be better memory footprint.

**Comment by mihails-strasuns-sociomantic** [comment]
It adds maintenance burden because now anyone changing that code needs to keep sure that stomped slices are not used anywhere else. But we could definitely try!

**Pull request merged**
