### PR TITLE
Add Travis support

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
The project will be built by Travis, and if there is a tag the resulting
packages will be uploaded to Bintray.

### CODE REVIEW

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
LGTM
Feel free to auto-merge after fixing build

**Comment by leandro-lucarella-sociomantic** [comment]
Updated with the latest beaver fixes. I could merge, after that this should be tagged 2.070.2.s11 to get the package uploaded?

**Comment by leandro-lucarella-sociomantic** [comment]
(I also updated the makefile a bit in case you want to have another look)

**Review by mihails-strasuns-sociomantic — APPROVED** [review]
I don't really understand why you switched it back to makefile but it doesn't matter.

**Comment by leandro-lucarella-sociomantic** [comment]
> I don't really understand why you switched it back to makefile but it doesn't matter.

To parallelize the build. It sort of started as a small addition the makefile and by the time I realized, I have moved everything :innocent:

**Comment by leandro-lucarella-sociomantic** [comment]
(and also, since I was rebuilding often, to avoid rebuilding dmd when I had problems only in druntime, because otherwise I spent too much time testing)

**Pull request merged**
