### PR TITLE
v70: Backport runtime configuration for coverage opts

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
I did a quick local test and it seems to work as expected. I guess after this is merged it should be also merged to v2.071.2.sX, right?

**Comment by mihails-strasuns-sociomantic** [comment]
You can provide separate PR for 2.071.2 by rebasing branch locally and generating patches again. I don't do merging in this repo because it doesn't work meaningfully with patches.

Can it wait until I get back to Riga btw? I don't have dmd/druntime testing setup configured on this laptop right now.

**Comment by leandro-lucarella-sociomantic** [comment]
OK. Sure, I will create the PR for v2.071 for now then.

**Comment by mihails-strasuns-sociomantic** [comment]
Tested, merging works. But I would like to resolve https://github.com/sociomantic-tsunami/makd/pull/115#issuecomment-364852627 first before proceeding with merge/tag.

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
