### PR TITLE
Build for bionic too

### LINKED ISSUE #23: Build for Ubuntu bionic
When building for bionic there are some compiler errors:

```
backend/go.c:82:5: error: narrowing conversion of '-1' from 'int' to 'mftype {aka unsigned int}' inside { } [-Wnarrowing]
     };
     ^
```

When adding `CXXFLAGS=-Wno-narrowing`, then we have:

```
backend/code.h:536:17: error: expected initializer before ‘cat’
 code * __pascal cat (code *c1 , code *c2 );
                 ^~~
```

### PR DESCRIPTION
**Pull request by mihails-strasuns**
Replaces https://github.com/sociomantic-tsunami/dmd-transitional/pull/24
Fixes #23

### CODE REVIEW

**Comment by mihails-strasuns** [comment]
Oh, damn, it fail at runtime too now :) back to drawing board.

**Review by leandro-lucarella-sociomantic — COMMENTED** [review]
Travis still says no.

**Comment by mihails-strasuns** [comment]
Ok, I fixed cycle issue but now building druntime just segfaults DMD.

How much do we need dmd-transitional for bionic exactly? :X

**Comment by leandro-lucarella-sociomantic** [comment]
We'll eventually need to build software that runs in Bionic :grimacing:

**Comment by mihails-strasuns** [comment]
After talking to @leandro-lucarella-sociomantic we agreed to only implement this for upcoming 2.078 branch - https://github.com/sociomantic-tsunami/dmd-transitional/pull/26

**Comment by mihails-strasuns** [comment]
Green!

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Comment by leandro-lucarella-sociomantic** [comment]
Release?

**Comment by mihails-strasuns** [comment]
Will there be final v6 base image any time soon?

**Comment by leandro-lucarella-sociomantic** [comment]
It doesn't change much, but now that the main breaking change of v6 is merged, I could do a final release for `develbase:v6`. The plan was to do the v6.0.0 only with base.

**Pull request merged**
