### PR TITLE
Preparations for final s12 release

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
FYI @mathias-lang-sociomantic  - will include the fix you asked for

@leandro-lucarella-sociomantic unless you have anything else in mind infra-wise for dmd-transitional, I'd like to tag final s12 release with this change.

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
I'll assume this is OK.

**Comment by mihails-strasuns-sociomantic** [comment]
May I push the tag?

**Comment by leandro-lucarella-sociomantic** [comment]
If you feel confident enough... If not you can release a `-rc1` for example :)

**Comment by mihails-strasuns-sociomantic** [comment]
https://github.com/sociomantic-tsunami/dmd-transitional/releases/tag/v2.070.2.s12

Now I presume we only need final cachalot v2 release before ocean can be switched to it, right?

**Comment by leandro-lucarella-sociomantic** [comment]
Yeah, it's already [in the repo](https://bintray.com/sociomantic-tsunami/dlang/dmd-transitional/v2.070.2.s12), but I'm blocked because of damn travis crashing `apt`. Can you test https://github.com/sociomantic-tsunami/cachalot/pull/18 locally to see if it works for you too?

**Pull request merged**
