### PR TITLE
Patch druntime to rework -profile=gc calculations

### PR DESCRIPTION
**Pull request by daniel-zullo**
Patch created out of dlang/druntime/pull/1846 targeting `v2.078.3.sX`

### CODE REVIEW

**Comment by daniel-zullo** [comment]
These are the diff from the original patch that I couldn't apply

```diff
diff --git a/src/gc/gcinterface.d b/src/gc/gcinterface.d
index c1620419..9f6ad462 100644
--- a/src/gc/gcinterface.d
+++ b/src/gc/gcinterface.d
@@ -187,4 +187,9 @@ interface GC
      *
      */
     bool inFinalizer() nothrow;
+
+    /*
+     *
+     */
+    void resetThreadLocalStats() nothrow @nogc;
 }
diff --git a/src/gc/impl/conservative/gc.d b/src/gc/impl/conservative/gc.d
index d9b51004..d62149ef 100644
--- a/src/gc/impl/conservative/gc.d
+++ b/src/gc/impl/conservative/gc.d
@@ -122,6 +122,9 @@ __gshared long extendTime;
 __gshared long otherTime;
 __gshared long lockTime;

+// thread-local counter
+size_t bytesAllocated;
+
 private
 {
     extern (C)
@@ -524,7 +527,9 @@ class ConservativeGC : GC
             sentinel_init(p, size);
             alloc_size = size;
         }
+
         gcx.log_malloc(p, size);
+        .bytesAllocated += size;

         return p;
     }
@@ -1227,6 +1232,12 @@ class ConservativeGC : GC

         stats.usedSize -= freeListSize;
         stats.freeSize += freeListSize;
+        stats.allocatedInCurrentThread = .bytesAllocated;
+    }
+
+    void resetThreadLocalStats() nothrow @nogc
+    {
+        .bytesAllocated = 0;
     }
 }

diff --git a/src/gc/impl/manual/gc.d b/src/gc/impl/manual/gc.d
index 3bcde758..beb5d521 100644
--- a/src/gc/impl/manual/gc.d
+++ b/src/gc/impl/manual/gc.d
@@ -271,4 +271,8 @@ class ManualGC : GC
     {
         return false;
     }
+
+    void resetThreadLocalStats() nothrow @nogc
+    {
+    }
 }
diff --git a/src/gc/impl/proto/gc.d b/src/gc/impl/proto/gc.d
index fa879a88..421228b1 100644
--- a/src/gc/impl/proto/gc.d
+++ b/src/gc/impl/proto/gc.d
@@ -100,6 +100,10 @@ class ProtoGC : GC
         return 0;
     }

+    void resetThreadLocalStats() nothrow @nogc
+    {
+    }
+
     void* malloc(size_t size, uint bits, const TypeInfo ti) nothrow
     {
         .gc_init_nothrow();
diff --git a/src/gc/proxy.d b/src/gc/proxy.d
index 2469b666..4bd5bce9 100644
--- a/src/gc/proxy.d
+++ b/src/gc/proxy.d
@@ -189,6 +189,11 @@ extern (C)
         return instance.stats();
     }

+    void gc_resetThreadLocalStats() nothrow @nogc
+    {
+        return instance.resetThreadLocalStats();
+    }
+
     void gc_addRoot( void* p ) nothrow @nogc
     {
         return instance.addRoot( p );


diff --git a/src/gc/impl/conservative/gc.d b/src/gc/impl/conservative/gc.d
index d62149ef..41c8a292 100644
--- a/src/gc/impl/conservative/gc.d
+++ b/src/gc/impl/conservative/gc.d
@@ -529,7 +529,7 @@ class ConservativeGC : GC
         }

         gcx.log_malloc(p, size);
-        .bytesAllocated += size;
+        .bytesAllocated += alloc_size;

         return p;
     }
```

**Comment by daniel-zullo** [comment]
@mihails-strasuns can you please have a quick look at the patch to check if these changes make sense to you? If it LGTY then I'd test with my application. Thanks in advance

**Comment by daniel-zullo** [comment]
I've just found out why I couldn't apply the differences. So I'll fix this PR accordingly and I guess it'll be fine to test it out with an app.

**Comment by daniel-zullo** [comment]
Updated the patch adding all the missing differences except the one from `src/gc/impl/proto/gc.d` as that file does not exist yet in `v2.078.3.sX`

**Comment by mihails-strasuns** [comment]
Looks good! Please tell if this works with nautica as expected and I will make new dmd-transitional release with this bit included.

**Comment by mihails-strasuns** [comment]
@daniel-zullo-sociomantic any updates?

**Comment by daniel-zullo** [comment]
I'm still testing it with 2 different apps. Please wait for a couple of days and I'll post my results/feedback. It seems it is working fine but it is **extremely** slow (which I guess it is expected to be).

**Comment by mihails-strasuns** [comment]
> which I guess it is expected to be

Depends on how slow exactly. I'd say within one order of magnitude is expected, more sounds suspicious. Before tweak with `resetThreadLocalStats` it was about 2 orders of magnitude slower.

**Comment by daniel-zullo** [comment]
> Depends on how slow exactly. I'd say within one order of magnitude is expected, more sounds suspicious. Before tweak with resetThreadLocalStats it was about 2 orders of magnitude slower.

I'm afraid something is wrong then. My app is more than 100 orders of magnitude slower

**Comment by mihails-strasuns** [comment]
10^100 times slower? :O

**Comment by daniel-zullo** [comment]
Sorry, my number was wrong. it is almost 10^3 times slower at the moment.

**Comment by mihails-strasuns** [comment]
Yeah that sounds like it is still calculating `GC.stats` before tweak. I will have to check patch again.

**Comment by mihails-strasuns** [comment]
Yup, confirmed, it is missing one last hack I used (to not calculate regular stats). Will post a patch in a moment.

**Comment by daniel-zullo** [comment]
> Yup, confirmed, it is missing one last hack I used (to not calculate regular stats). Will post a patch in a moment.

Great!

**Comment by mihails-strasuns** [comment]
Pushed one commit to this branch

**Comment by mihails-strasuns** [comment]
FYI: it all comes down to this https://github.com/sociomantic-tsunami/dmd-transitional/pull/34/commits/50ff065d145d5f5abc55903cfe67fb0f953df61d#diff-d4dea6e3509b0f981e6d9af5a8128a16R107 (not calculating regular expensive `GC.stats` when only TLS counter is needed)

**Comment by daniel-zullo** [comment]
Good to know. I'll give it a try right now and report once I have results

**Comment by daniel-zullo** [comment]
I confirm the new patch made a huge difference in the performance. Anyway please wait for my feedback before merging it as I'll go for a long test run now.

**Comment by daniel-zullo** [comment]
@mihails-strasuns all good on my side. The new patch works fine and super fast. I managed to find sneaky GC allocations thanks to this patch. So I'd say feel free to merge it if you are happy with the changes.

**Comment by mihails-strasuns** [comment]
Great! Releasing new dmd-transitional in a moment. Can you ping me from the app PR which fixes those allocations? I am curious to know what kind it was.

**Comment by daniel-zullo** [comment]
> Great! Releasing new dmd-transitional in a moment. Can you ping me from the app PR which fixes those allocations? I am curious to know what kind it was.

Sure

**Pull request merged**
